### ISSUE TITLE
Feature request: Extend a width/height types to pass values like '100%'

### ISSUE THREAD

**Issue by skident** [douglasjunior/react-native-gradient-shimmer#1]
It would be nice to have ability to pass values like 100% to the width property, to fully cover a parent component.

**Comment by douglasjunior** [comment]
This is not possible, because we use the `number` to calculate some values based on parent size.

https://github.com/douglasjunior/react-native-gradient-shimmer/blob/d4a28e8e4aae5d7e41bbd5f7a177e36771282380/src/GradientShimmer.tsx#L162-L164

If you need to create some values relative, you can use the `width` of the parent View or the `width` from `useWindowDimensions` like in the Sample project:

https://github.com/douglasjunior/react-native-gradient-shimmer/blob/d4a28e8e4aae5d7e41bbd5f7a177e36771282380/Sample/App.tsx#L99-L101
